# Generated by Django 5.2.4 on 2025-08-09 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Email address", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, help_text="User avatar", null=True, upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number in format: '+999999999'",
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("User", "user"), ("Admin", "admin")],
                default="User",
                help_text="User role",
                max_length=5,
            ),
        ),
    ]
