# Generated by Django 5.2.4 on 2025-08-09 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Ad",
                "verbose_name_plural": "Ads",
            },
        ),
        migrations.AlterField(
            model_name="ad",
            name="author",
            field=models.ForeignKey(
                help_text="The user who created the ad.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="The date and time the ad was created."
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="description",
            field=models.TextField(help_text="A detailed description of the ad."),
        ),
        migrations.AlterField(
            model_name="ad",
            name="price",
            field=models.PositiveIntegerField(
                help_text="The price of the ad (in RUR)."
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="title",
            field=models.CharField(help_text="The title of the ad.", max_length=255),
        ),
    ]
