# Generated by Django 5.2.4 on 2025-08-09 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_ad_options_alter_ad_author_alter_ad_created_at_and_more"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["created_at"], "verbose_name": "Reviews"},
        ),
        migrations.AlterField(
            model_name="review",
            name="ad",
            field=models.ForeignKey(
                help_text="Ad to which the review belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="ads.ad",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                help_text="User who wrote the review.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="The date and time the review was created"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(help_text="Content of the review."),
        ),
    ]
